In [89]:
import numpy as np
import pandas as pd
from numpy import random

# : Create a 3x3x3 array with random values

In [90]:
a = np.random.random((3,3,3))
print(a)

[[[0.20592264 0.80794964 0.35302608]
  [0.9198037  0.85117441 0.60800128]
  [0.8677465  0.09355955 0.59815636]]

 [[0.07941687 0.11810066 0.89119775]
  [0.90998214 0.8158598  0.71643017]
  [0.17628482 0.92135677 0.13265335]]

 [[0.69591476 0.19517738 0.28269108]
  [0.12644002 0.92427603 0.48835428]
  [0.84415453 0.8826246  0.79484245]]]


# : Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [91]:
import numpy as np
m = np.zeros((5,5))
m[1][0] = 1
m[2][1] = 2
m[3][2] = 3
m[4][3] = 4
print(m)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# : Create a 8x8 matrix and fill it with a checkerboard pattern

In [92]:
import numpy as np
a= np.zeros((8,8))
a[1::2,::2], a[::2,1::2] = 1, 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# : Normalize a 5 x 5 Random Matrix

In [93]:
import numpy as np
from numpy import random

arr = np.random.randint(5,50,(5,5)) # random numpy array of shape (4,5)
print("Random Array : ")
print(arr)

# To normalize given array 'arr' using Linear Algebra 'linalg' from numpy
norm = np.linalg.norm(arr)
norm_arr = arr/norm
print(end= '\n')
print("Normalized Random Array : ")
print(norm_arr)


Random Array : 
[[40 45 36  8  9]
 [13  5 15  9 32]
 [20 44 36 26 39]
 [26 46 29 46 14]
 [45 29 37 39 27]]

Normalized Random Array : 
[[0.2537497  0.28546841 0.22837473 0.05074994 0.05709368]
 [0.08246865 0.03171871 0.09515614 0.05709368 0.20299976]
 [0.12687485 0.27912467 0.22837473 0.1649373  0.24740596]
 [0.1649373  0.29181215 0.18396853 0.29181215 0.08881239]
 [0.28546841 0.18396853 0.23471847 0.24740596 0.17128105]]


# : How to find common values between two arrays?


In [94]:
import numpy as np

arr1 = [2,4,6,12,18]
arr2 = [3,6,9,18,27,21]

common_values = np.intersect1d(arr1, arr2)
print("Common values between given two arrays are: ", common_values)

Common values between given two arrays are:  [ 6 18]


# : How to get the dates of yesterday, today and tomorrow?

In [95]:
import datetime


today=datetime.date.today()

yesterday = today - datetime.timedelta(days=1)

tomorrow  = today + datetime.timedelta(days=1)

print(yesterday.strftime('%d/%m/%Y'))
print(end = '\n')
print(today.strftime('%m-%d-%Y'))
print(end = '\n')
print(tomorrow)

30/03/2021

03-31-2021

2021-04-01


# : Consider two random array A and B, check if they are equal

In [96]:
from numpy import random
arr1 = random.randint(2, 10 , (3,3), dtype =int)
arr2 = random.randint(2,10, (3,3), dtype =int)

print("First array: ", arr1, end= '\n')
print("Second array: ", arr2, end= '\n')

if (arr1==arr2).all():
    print("The two given arrays are Equal.")
else:
    print("The two given arrays are not Equal.")


First array:  [[3 4 2]
 [7 9 9]
 [5 3 8]]
Second array:  [[6 7 8]
 [5 2 6]
 [8 4 9]]
The two given arrays are not Equal.


# : Create random vector of size 10 and replace the maximum value by 0

In [97]:
import numpy as np
import random

rvec = np.random.rand(10)
print(rvec)

print('\n')

max_num = np.where(rvec == rvec.max())
rvec[max_num] = 0

print(rvec)


[0.67515173 0.31279435 0.13999914 0.64160831 0.24074236 0.70580945
 0.72309781 0.31311053 0.01071366 0.15424407]


[0.67515173 0.31279435 0.13999914 0.64160831 0.24074236 0.70580945
 0.         0.31311053 0.01071366 0.15424407]


# : How to print all the values of an array?

In [106]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# : Subtract the mean of each row of a matrix

In [116]:
import numpy as np
import random

arr = np.random.randint(2,15, (3,3), dtype= int)
print("Given Array: ", arr, end='\n \n')

new_arr = arr - np.mean(arr, axis =1, keepdims=True)
print("New Array with Subtracted mean is: ", end='\n')
print(new_arr)

Given Array:  [[ 3 11  8]
 [12  9  9]
 [ 4 12  3]]
 
New Array with Subtracted mean is: 
[[-4.33333333  3.66666667  0.66666667]
 [ 2.         -1.         -1.        ]
 [-2.33333333  5.66666667 -3.33333333]]


# : Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [137]:
def repeated(vec):
    dup_items = set()
    uniq_items = []
    for x in vec:
        if x not in dup_items:
            uniq_items.append(x)
            dup_items.add(x)
    return uniq_items
    
import numpy as np
vec = np.array([3,2,6,7,9])
index = np.array([4,2,3,1,2])
new_index=repeated(index)
for a in new_index:
    vec[a]=vec[a]+1
print(vec)

[ 3  3  7  8 10]


# : How to get the diagonal of a dot product?

In [121]:
arr1 = np.array([[1,2], [5,6], [9,11]])
arr2 = np.array([[2,7,5],[3,1,4]])

arr_prod = arr1.dot(arr2)
print(arr_prod)
print('\n')
print(np.diagonal(arr_prod))

[[ 8  9 13]
 [28 41 49]
 [51 74 89]]


[ 8 41 89]


# : How to find the most frequent value in an array?

In [128]:
import numpy as np
from scipy import stats

arr = np.array([12,3,2,5,3,6,3,9,10])
feq= stats.mode(arr)
print(feq[0])

#bin = np.bincount(arr)
#print(bin.argmax())

[3]


# : How to get the n largest values of an array

In [129]:
import numpy as np

arr = np.array([21, 13, 41, 29, 15, 7, 30, 33])
n=4
lar_arr = arr[np.argsort(arr)]
print(lar_arr[-n:])

[29 30 33 41]


# : How to create a record array from a regular array?

In [130]:
import numpy as np

arr1 = np.array([("Abhishek", 34, 189),
                 ("Hanu", 31, 163),
             ("Abhinav", 32, 174)])
print("Regular Array: \n", arr1)
#print(arr1)
print("\n Record Array;")

fin_arr = np.core.records.fromarrays(arr1.T,
                              names='NAME, AGE, Height')
print(fin_arr)

Regular Array: 
 [['Abhishek' '34' '189']
 ['Hanu' '31' '163']
 ['Abhinav' '32' '174']]

 Record Array;
[('Abhishek', '34', '189') ('Hanu', '31', '163') ('Abhinav', '32', '174')]
